#! /bin/sh

pgreep -x sxhkd > /dev/null || sxhkd &

bspc monitor DVI-D-0 -d 1 2 3 4 5
bspc monitor HDMI-0 -d 1 2 3 4 5
bspc monitor HDMI-1 -d 1 2 3 4 5 6 7 8 9 10
bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

# Some tweaks for system

### Set ru, us layout in kbdx
setxkbmap -layout us,ru -option grp:alt_shift_toggle